### ISSUE TITLE
Uppercase stay active on iOS

### ISSUE THREAD

**Issue by lukasleitsch** [sylvainjule/kirby-markdown-field#67]
The native behavior of writing the first character in uppercase is not working on iOS.

## Steps to reproduce 
1. Open a page with an active markdown field in the iOS Safari browser
2. Set the focus into the markdown field
3. Tap the shift button on the iOS keyboard
4. Start typing a text

The markdown field writes every character in uppercase. The markdown field should write only the first character uppercase and should switch back to the lowercase after the first character.

**Comment by sylvainjule** [comment]
Unfortunately it is a [known issue](https://github.com/codemirror/CodeMirror/issues/3403) with Codemirror, with no satysfying workaround so far. I don't think we'll fix this.

**Comment by fabianmichael** [comment]
@lukasleitsch

**Comment by fabianmichael** [comment]
@lukasleitsch I just updated the plugin to the latest version of CodeMirror, which seems to have solved this issue (see https://github.com/codemirror/CodeMirror/issues/3403#issuecomment-481981454). Please test, if you still got problems with the uppercase key on iOS. If not, this issue can be closed. :-)

**Comment by lukasleitsch** [comment]
Thanks for your update. Unfortunately, your update doesn't solve the issue for me. 

I used `dev-master` in the `composer.json` is there a cache that has to be deleted? To make sure any files have replaced.

**Comment by alvarovinagre** [comment]
@fabianmichael Tried here as well, but the issue is still persisting. Even tried to set 'community.markdown-field.autocapitalize' => 'off', on the config.php, but still no results.

If anyone finds a workaround please let us know :-)

**Comment by alvarovinagre** [comment]
Thank you @sylvainjule, updating to the latest version of the plugin did it for me. 👍

**Comment by sylvainjule** [comment]
That makes two of us, I'll close this then. Don't hesitate to ask to reopen if needed :)
